[agent]
  interval = "1s"
  flush_interval = "1s"

# 1. Dados da Bancada / ESP32
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["teg/esp32/telemetria", "teg/bancada/telemetria"]
  data_format = "json"
  name_override = "esp32_telemetry"

# 2. Dados Ideais do ANSYS
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["teg/ansys/telemetria"]
  data_format = "json"
  name_override = "ansys_telemetry"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "my-super-secret-admin-token"
  organization = "teg_org"
  bucket = "teg_telemetry"