apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: teg_org
      defaultBucket: teg_telemetry
    secureJsonData:
      token: my-super-secret-admin-token
    isDefault: true